version: "3.3"

networks:
  external:
  internal:
    internal: false

services:
  nginx:
    image: "alqutami/rtmp-hls"
    ports:
      - "127.0.0.1:1337:1337"
    volumes:
      - ./docker-compose/rtmp-configs/nginx-rtmp/nginx.conf.template:/etc/nginx/nginx.conf
      - /home/ubuntu/miracle-data/media:/mnt/media
      - /home/ubuntu/miracle-data/streaming/hls:/mnt/hls
    depends_on:
      - miracle-backend
      - miracle-frontend
    networks:
      - external
      - internal
  ome:
    image: "airensoft/ovenmediaengine:0.12.9"
    ports:
      - "1935:1935"
      - "3333:3333"
      - "3478:3478"
      - "8082:8080"
      - "10000:10000/udp"
    # network_mode: "host"
    volumes:
      - ./docker-compose/rtmp-configs/ome/:/opt/ovenmediaengine/bin/origin_conf
      - ./docker-compose/rtmp-configs/ome_edge/:/opt/ovenmediaengine/bin/edge_conf
  rethinkdb:
    image: "rethinkdb"
    volumes:
      - /home/ubuntu/miracle-data/db:/data
    networks:
      - internal
  miracle-backend:
    build:
      context: "."
      dockerfile: "./backend.Dockerfile"
    ports:
      - "4000:4000"
    depends_on:
      - rethinkdb
    volumes:
      - ./docker-compose/docker.miracle-tv.json:/conf/config.json
      - /home/ubuntu/miracle-data:/data/miracle-tv
    environment:
      - MIRACLE_CONFIG=/conf/config.json
    networks:
      - internal
  miracle-frontend:
    build:
      context: "."
      dockerfile: "./frontend.Dockerfile"
    networks:
      - internal
    ports:
      - "3000:3000"
    depends_on:
      - miracle-backend
    command:
      [
        "./wait-for",
        "-t",
        "30",
        "http://miracle-backend:4000/api/hook/ping",
        "--",
        "yarn",
        "run:client",
      ]
    environment:
      - NEXT_PUBLIC_MEDIA_URL=https://miracle-tv.live/media
      - NEXT_PUBLIC_SOCKET_PREFIX=/api
      - NEXT_PUBLIC_ENV=production
      - NEXT_PUBLIC_API_URL=https://miracle-tv.live/api
