version: "3.3"

services:
  nginx:
    image: "alqutami/rtmp-hls"
    ports:
      - "1935:1935"
      - "1337:1337"
    volumes:
      - ./docker-compose/rtmp-configs/nginx-rtmp/nginx.conf.template:/etc/nginx/nginx.conf
      - /home/ubuntu/miracle-data/media:/mnt/media
    depends_on:
      - miracle-backend
      - miracle-frontend
  rethinkdb:
    image: "rethinkdb"
    volumes:
      - /home/ubuntu/miracle-data/db:/data
  miracle-backend:
    build:
      context: "."
      dockerfile: "./backend.Dockerfile"
    ports:
      - "4000:4000"
    depends_on:
      - rethinkdb
    volumes:
      - ./docker-compose/docker.miracle-tv.json:/conf/config.json
      - /home/ubuntu/miracle-data:/data/miracle-tv
    environment:
      - MIRACLE_CONFIG=/conf/config.json
  miracle-frontend:
    build:
      context: "."
      dockerfile: "./frontend.Dockerfile"
    ports:
      - "3000:3000"
    depends_on:
      - miracle-backend
    environment:
      - NEXT_PUBLIC_MEDIA_URL=http://miracle-tv.live:1337/media
      - NEXT_PUBLIC_ENV=production
      - NEXT_PUBLIC_API_URL=http://miracle-tv.live:1337/api/graphql
